/*
------------------------------------------------------------------------------
 Author       : Sanvi Y B and Sai Nithya M
 Designation  : Students
 Organization : MSRIT
------------------------------------------------------------------------------
*/
// =============================================================================
// rom.v – AXI-Lite Read-Only Memory (ROM)
// =============================================================================
// ASIC-clean version:
//   SYNTHESIS path : synthesizable case-statement ROM (generated from rom.hex)
//   Simulation path: $readmemh for flexibility
//
// All inline register initializers removed; reset drives all state registers.
// =============================================================================

`timescale 1ns / 1ps

module rom #(
    parameter MEM_DEPTH = 2048,
    parameter INIT_FILE = "rom.hex"
)(
    input         clk,
    input         reset,

    // AXI-Lite Write Address Channel
    input  [31:0] s_axi_awaddr,
    input         s_axi_awvalid,
    output        s_axi_awready,

    // AXI-Lite Write Data Channel
    input  [31:0] s_axi_wdata,
    input  [ 3:0] s_axi_wstrb,
    input         s_axi_wvalid,
    output        s_axi_wready,

    // AXI-Lite Write Response Channel
    output [ 1:0] s_axi_bresp,
    output        s_axi_bvalid,
    input         s_axi_bready,

    // AXI-Lite Read Address Channel
    input  [31:0] s_axi_araddr,
    input         s_axi_arvalid,
    output        s_axi_arready,

    // AXI-Lite Read Data Channel
    output [31:0] s_axi_rdata,
    output [ 1:0] s_axi_rresp,
    output        s_axi_rvalid,
    input         s_axi_rready
);

    // ============================================================
    // WRITE CHANNEL (ROM is read-only; accept & discard writes)
    // All registers are reset-driven — no inline initializers.
    // ============================================================
    reg aw_pend;
    reg w_pend;
    reg b_vld;

    assign s_axi_awready = !aw_pend;
    assign s_axi_wready  = !w_pend;
    assign s_axi_bresp   = 2'b00;  // OKAY
    assign s_axi_bvalid  = b_vld;

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            aw_pend <= 1'b0;
            w_pend  <= 1'b0;
            b_vld   <= 1'b0;
        end else begin
            if (s_axi_awvalid && !aw_pend)
                aw_pend <= 1'b1;

            if (s_axi_wvalid && !w_pend)
                w_pend <= 1'b1;

            if (aw_pend && w_pend && !b_vld) begin
                b_vld   <= 1'b1;
                aw_pend <= 1'b0;
                w_pend  <= 1'b0;
            end

            if (b_vld && s_axi_bready)
                b_vld <= 1'b0;
        end
    end

    // ============================================================
    // READ CHANNEL
    // ============================================================
    // r_valid_r and r_data_r declared here for both paths.
    // In SYNTHESIS: the read FSM is embedded in the case block below.
    // In SIMULATION: $readmemh + array lookup.
    // ============================================================

    reg        r_valid_r;
    reg [31:0] r_data_r;

    assign s_axi_arready = !r_valid_r;
    assign s_axi_rdata   = r_data_r;
    assign s_axi_rresp   = 2'b00;  // OKAY
    assign s_axi_rvalid  = r_valid_r;

`ifdef SYNTHESIS
    // ----------------------------------------------------------------
    // SYNTHESIS PATH: synthesizable ROM via case statement
    // Generated by fw/gen_rom_case.py from rom.hex
    // Yosys infers this as a read-only LUT/memory.
    // ----------------------------------------------------------------
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            r_data_r  <= 32'h00000013;
            r_valid_r <= 1'b0;
        end else begin
            if (s_axi_arvalid && !r_valid_r) begin
                r_valid_r <= 1'b1;
                case (s_axi_araddr[12:2])
                    11'd0:  r_data_r <= 32'h00020137;
                    11'd1:  r_data_r <= 32'hFFC10113;
                    11'd2:  r_data_r <= 32'h00010297;
                    11'd3:  r_data_r <= 32'hFF828293;
                    11'd4:  r_data_r <= 32'h00010317;
                    11'd5:  r_data_r <= 32'hFF030313;
                    11'd6:  r_data_r <= 32'h0062D863;
                    11'd7:  r_data_r <= 32'h0002A023;
                    11'd8:  r_data_r <= 32'h00428293;
                    11'd9:  r_data_r <= 32'hFF5FF06F;
                    11'd10: r_data_r <= 32'h008000EF;
                    11'd11: r_data_r <= 32'h0000006F;
                    11'd12: r_data_r <= 32'h00A00613;
                    11'd13: r_data_r <= 32'h08C00593;
                    11'd14: r_data_r <= 32'h100006B7;
                    11'd15: r_data_r <= 32'h04800713;
                    11'd16: r_data_r <= 32'h00058793;
                    11'd17: r_data_r <= 32'h00178793;
                    11'd18: r_data_r <= 32'h00E68023;
                    11'd19: r_data_r <= 32'h0007C703;
                    11'd20: r_data_r <= 32'hFE071AE3;
                    11'd21: r_data_r <= 32'hFFF60613;
                    11'd22: r_data_r <= 32'hFE0612E3;
                    11'd23: r_data_r <= 32'h10000737;
                    11'd24: r_data_r <= 32'h100006B7;
                    11'd25: r_data_r <= 32'h10000637;
                    11'd26: r_data_r <= 32'h00870713;
                    11'd27: r_data_r <= 32'h00468693;
                    11'd28: r_data_r <= 32'h00072783;
                    11'd29: r_data_r <= 32'h0027F793;
                    11'd30: r_data_r <= 32'hFE078CE3;
                    11'd31: r_data_r <= 32'h0006C783;
                    11'd32: r_data_r <= 32'h0FF7F793;
                    11'd33: r_data_r <= 32'h00F60023;
                    11'd34: r_data_r <= 32'hFE9FF06F;
                    11'd35: r_data_r <= 32'h6C6C6548;
                    11'd36: r_data_r <= 32'h6544206F;
                    11'd37: r_data_r <= 32'h6B617065;
                    11'd38: r_data_r <= 32'h6F726620;
                    11'd39: r_data_r <= 32'h694E206D;
                    11'd40: r_data_r <= 32'h74696C65;
                    11'd41: r_data_r <= 32'h00000A21;
                    default: r_data_r <= 32'h00000013; // NOP
                endcase
            end
            if (r_valid_r && s_axi_rready)
                r_valid_r <= 1'b0;
        end
    end

`else
    // ----------------------------------------------------------------
    // SIMULATION PATH: load from hex file via $readmemh
    // ----------------------------------------------------------------
    reg [31:0] mem [0:MEM_DEPTH-1];
    integer i;

    initial begin : rom_init
        reg [1023:0] rom_path;

        // Fill with NOPs first
        for (i = 0; i < MEM_DEPTH; i = i + 1)
            mem[i] = 32'h00000013;

        // Allow override via plusarg, otherwise use parameter
        if ($value$plusargs("romhex=%s", rom_path)) begin
            $readmemh(rom_path, mem);
            $display("[ROM] loaded from plusarg: %0s", rom_path);
        end else if (INIT_FILE != "") begin
            $readmemh(INIT_FILE, mem);
            $display("[ROM] loaded from parameter: %s", INIT_FILE);
        end else begin
            $display("[ROM] WARNING: ROM contains NOPs only");
        end
    end

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            r_valid_r <= 1'b0;
            r_data_r  <= 32'h00000013;
        end else begin
            if (s_axi_arvalid && !r_valid_r) begin
                r_data_r  <= mem[s_axi_araddr[$clog2(MEM_DEPTH)+1 : 2]];
                r_valid_r <= 1'b1;
            end
            if (r_valid_r && s_axi_rready)
                r_valid_r <= 1'b0;
        end
    end
`endif

endmodule
