#!/usr/bin/env python3
# =============================================================================
# gen_rom_case.py  –  Convert rom.hex → synthesizable Verilog ROM case block
# =============================================================================
# Usage:
#   python3 gen_rom_case.py <rom.hex> <mem_depth> > rom_case.vh
#
# The output Verilog snippet is included inside rom.v under `ifdef SYNTHESIS.
# Yosys infers this as a read-only memory (ROM) from the case statement.
# =============================================================================

import sys

def gen_rom_case(hex_file, mem_depth):
    words = []

    with open(hex_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('//') or line.startswith('@'):
                continue
            # Each line may contain one 8-hex-digit word
            parts = line.split()
            for p in parts:
                words.append(int(p, 16))

    # Pad to mem_depth with NOP (addi x0,x0,0 = 0x00000013)
    nop = 0x00000013
    while len(words) < mem_depth:
        words.append(nop)

    addr_bits = (mem_depth - 1).bit_length()

    lines = []
    lines.append("// AUTO-GENERATED by gen_rom_case.py — DO NOT EDIT MANUALLY")
    lines.append(f"// ROM depth: {mem_depth} words  ({mem_depth*4} bytes)")
    lines.append(f"// Source: {hex_file}")
    lines.append("")
    lines.append(f"    always @(posedge clk or posedge reset) begin")
    lines.append(f"        if (reset) begin")
    lines.append(f"            r_data_r  <= 32'h00000013;")
    lines.append(f"            r_valid_r <= 1'b0;")
    lines.append(f"        end else begin")
    lines.append(f"            if (s_axi_arvalid && !r_valid_r) begin")
    lines.append(f"                r_valid_r <= 1'b1;")
    lines.append(f"                case (s_axi_araddr[{addr_bits+1}:2])")
    for i, w in enumerate(words):
        if w != nop:  # Only emit non-NOP entries
            lines.append(f"                    {addr_bits}'d{i}: r_data_r <= 32'h{w:08X};")
    lines.append(f"                    default: r_data_r <= 32'h00000013; // NOP")
    lines.append(f"                endcase")
    lines.append(f"            end")
    lines.append(f"            if (r_valid_r && s_axi_rready)")
    lines.append(f"                r_valid_r <= 1'b0;")
    lines.append(f"        end")
    lines.append(f"    end")

    return "\n".join(lines)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <rom.hex> <mem_depth>", file=sys.stderr)
        sys.exit(1)

    hex_file  = sys.argv[1]
    mem_depth = int(sys.argv[2])

    print(gen_rom_case(hex_file, mem_depth))
