/*
------------------------------------------------------------------------------
 Author       : Deepak
 Designation  : Sr. VLSI Engineer
 Organization : NIELIT CoE
------------------------------------------------------------------------------

File: tb_top.cpp

Purpose
-------
This file implements a **Verilator C++ testbench** for a PicoRV32-based SoC that
uses an **AXI-Lite bus and a UART peripheral**.

The testbench replaces the traditional Verilog testbench with a C++ program
that drives the DUT (Device Under Test) generated by Verilator.

This testbench performs the following tasks:

1. Generates the system clock and reset.
2. Monitors the UART TX line to decode outgoing UART data.
3. Simulates UART RX input to send commands to the SoC.
4. Waits for firmware greeting messages from the CPU.
5. Sends the command "PING" through UART RX.
6. Verifies the echo response from the firmware.

System Context
--------------
Used in a **simulation environment** for validating a small RISC-V SoC.

Data flow:

        +---------------------+
        |   Firmware (CPU)    |
        |   PicoRV32 Core     |
        +----------+----------+
                   |
                   | UART TX
                   v
           +---------------+
           |   TX Monitor  |  (decodes outgoing UART)
           +---------------+
                   |
                   v
              rx_fifo queue

           +---------------+
           |   RX Driver   |  (injects UART RX data)
           +---------------+
                   ^
                   |
             Test Sequencer

The testbench verifies correct firmware execution and UART communication.
*/

// =============================================================================
// tb_top.cpp – Verilator C++ Testbench for PicoRV32 AXI-Lite SoC (UART TX+RX)
// =============================================================================
//
// Design: a single master tick-loop drives every clock edge.
//
// Two concurrent state-machines run inside that loop exactly as the two
// Verilog `initial` blocks did:
//
//   1. TX_MONITOR
//      - Detects falling edge on uart_tx
//      - Samples UART frame (8N1 format)
//      - Pushes received bytes into rx_fifo
//
//   2. TEST_SEQ
//      - Waits for greeting messages
//      - Flushes FIFO
//      - Sends command "PING"
//      - Checks echoed response
//
// Both state machines advance once per simulation clock tick.
// This emulates Verilog’s event-driven simulation model.
// =============================================================================

#include "Vtop.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <queue>

// ─────────────────────────────────────────────────────────────────────────────
// UART Timing Parameters
// ─────────────────────────────────────────────────────────────────────────────
//
// System clock: 50 MHz → 20 ns period
// UART baud rate: 115200
//
// Clocks per UART bit ≈ 50,000,000 / 115200 ≈ 434
//
// These constants match the UART timing used in the RTL.
//
#define UART_BIT_CYCLES   434          // clock cycles per UART bit
#define BAUD_HALF_CYC     217          // half-bit delay (used for mid-bit sampling)
//
#define BAUD_FULL_CYC     434          // full UART bit period
#define RESET_CYCLES      10           // number of clock cycles reset is asserted
#define SIM_TIMEOUT_CYC   25000000ULL  // simulation timeout (≈500 ms)

// ─────────────────────────────────────────────────────────────────────────────
// Global Simulation Time
// ─────────────────────────────────────────────────────────────────────────────
//
// Verilator uses "simulation time" for waveform dumping (VCD).
// Each clock edge increments this value.
//
static vluint64_t sim_time = 0;

double sc_time_stamp ()
{
    return (double)sim_time;
}

// ─────────────────────────────────────────────────────────────────────────────
// DUT Instance
// ─────────────────────────────────────────────────────────────────────────────
//
// Vtop is the C++ model generated by Verilator from the Verilog top module.
//
static Vtop          *top = nullptr;
static VerilatedVcdC *tfp = nullptr;

// ─────────────────────────────────────────────────────────────────────────────
// Shared FIFO (UART monitor → test sequencer)
// ─────────────────────────────────────────────────────────────────────────────
//
// When the UART TX monitor decodes a byte transmitted by the DUT,
// it pushes the byte into this queue.
//
// The test sequencer later reads from this queue.
//
static std::queue<uint8_t> rx_fifo;


// ─────────────────────────────────────────────────────────────────────────────
// Clock Tick Function
// ─────────────────────────────────────────────────────────────────────────────
//
// Drives one full clock cycle:
//     clk = 0 → evaluate
//     clk = 1 → evaluate
//
// Each edge is dumped into the waveform file.
//
static inline void tick()
{
    top->clk = 0;
    top->eval();
    if (tfp) tfp->dump(sim_time);
    sim_time++;

    top->clk = 1;
    top->eval();
    if (tfp) tfp->dump(sim_time);
    sim_time++;
}


// =============================================================================
// UART TX Monitor
// =============================================================================
//
// This module monitors the DUT's UART transmit pin (uart_tx).
//
// It decodes the serial stream into bytes using the standard UART format:
//
//      1 start bit
//      8 data bits (LSB first)
//      1 stop bit
//
// Format: 8N1
//
// The monitor pushes received bytes into rx_fifo.
// This allows the testbench to inspect firmware output.
//

struct TxMonitor {

    // UART decode state machine
    enum State { WAIT_FALL, HALF_BIT, SAMPLE_BITS, STOP_BIT };

    State    state     = WAIT_FALL;

    int      clk_cnt   = 0;     // clock counter for bit timing
    uint8_t  byte_val  = 0;     // reconstructed byte
    int      bit_i     = 0;     // current bit index
    int      prev_tx   = 1;     // previous TX level

    int      hello_count = 0;   // count greeting messages

    // Called once per simulation tick
    void step()
    {
        int cur_tx = top->uart_tx;
        

        switch (state) {

        // Wait for falling edge indicating start bit
        case WAIT_FALL:
            if (prev_tx == 1 && cur_tx == 0) {
                clk_cnt = BAUD_HALF_CYC - 1;  // sample in middle of bit
                state   = HALF_BIT;
            }
            break;

        // Wait half-bit to confirm start bit
        case HALF_BIT:
            if (clk_cnt-- == 0) {

                // verify start bit still low
                if (top->uart_tx == 0) {
                    byte_val = 0;
                    bit_i    = 0;
                    clk_cnt  = BAUD_FULL_CYC - 1;
                    state    = SAMPLE_BITS;
                } else {
                    state = WAIT_FALL;  // false start
                }
            }
            break;

        // Sample each of the 8 data bits
        case SAMPLE_BITS:
            if (clk_cnt-- == 0) {

                // LSB-first bit reconstruction
                if (top->uart_tx)
                    byte_val |= (1u << bit_i);

                bit_i++;

                if (bit_i == 8) {
                    clk_cnt = BAUD_FULL_CYC - 1;
                    state   = STOP_BIT;
                } else {
                    clk_cnt = BAUD_FULL_CYC - 1;
                }
            }
            break;

        // Stop bit phase
        case STOP_BIT:
            if (clk_cnt-- == 0) {

                // Byte received
                putchar((char)byte_val);
                fflush(stdout);

                rx_fifo.push(byte_val);

                // Detect greeting messages
                if (byte_val == '\n') {

                    hello_count++;

                    printf("\n[TB] Greeting message count = %d\n", hello_count);

                    if (hello_count == 10) {
                        printf("\n============================================\n");
                        printf(" 10 GREETING MESSAGES RECEIVED\n");
                        printf(" UART OUTPUT VERIFIED\n");
                        printf("============================================\n\n");
                    }
                }

                // return to idle
                prev_tx = 1;
                state   = WAIT_FALL;
                return;
            }
            break;
        }

        prev_tx = cur_tx;
    }
};


// =============================================================================
// UART RX Driver
// =============================================================================
//
// Generates UART input to the DUT.
//
// Converts bytes into UART serial format (8N1):
//
//      start bit
//      8 data bits (LSB first)
//      stop bit
//
// Used to inject commands into the firmware.
//

struct RxDriver {

    enum State { IDLE, START, DATA, STOP, GAP };

    State   state    = IDLE;

    int     clk_cnt  = 0;
    uint8_t byte_val = 0;
    int     bit_i    = 0;

    bool    done     = false;

    // Queue byte to transmit
    void enqueue(uint8_t b)
    {
        byte_val = b;
        done     = false;

        clk_cnt  = UART_BIT_CYCLES - 1;

        state    = START;

        // start bit
        top->uart_rx = 0;
    }

    bool is_idle() const { return state == IDLE; }
    bool is_done() const { return done; }

    void step()
    {
        if (state == IDLE) return;

        switch (state) {

        case START:
            if (clk_cnt-- == 0) {

                bit_i   = 0;
                clk_cnt = UART_BIT_CYCLES - 1;

                // transmit first data bit
                top->uart_rx = (byte_val >> bit_i) & 1;

                state = DATA;
            }
            break;

        case DATA:
            if (clk_cnt-- == 0) {

                bit_i++;

                if (bit_i == 8) {

                    clk_cnt      = UART_BIT_CYCLES - 1;

                    // stop bit
                    top->uart_rx = 1;

                    state = STOP;

                } else {

                    clk_cnt      = UART_BIT_CYCLES - 1;

                    // transmit next bit
                    top->uart_rx = (byte_val >> bit_i) & 1;
                }
            }
            break;

        case STOP:
            if (clk_cnt-- == 0) {

                // extra idle time for firmware polling
                clk_cnt      = UART_BIT_CYCLES * 3 - 1;

                top->uart_rx = 1;

                state = GAP;
            }
            break;

        case GAP:
            if (clk_cnt-- == 0) {

                state = IDLE;
                done  = true;
            }
            break;

        default:
            break;
        }
    }
};


// =============================================================================
// main()
// =============================================================================

int main(int argc, char **argv)
{
    Verilated::commandArgs(argc, argv);

    top = new Vtop;

    Verilated::traceEverOn(true);

    tfp = new VerilatedVcdC;
    top->trace(tfp, 99);

    tfp->open("tb_top.vcd");

    // Initial signal state
    top->clk     = 0;
    top->reset   = 1;
    top->uart_rx = 1;

    printf("--------------------------------------------------\n");
    printf(" UART SoC Simulation Started\n");
    printf("--------------------------------------------------\n");

    // Reset sequence
    for (int i = 0; i < RESET_CYCLES; i++)
        tick();

    top->reset = 0;

    printf("\n[TB] UART Monitor Started\n");

    // Instantiate state machines
    TxMonitor mon;
    RxDriver  drv;

    // Test phases
    enum Phase { PH_GREETING, PH_FLUSH, PH_PING_SEND, PH_ECHO_WAIT, PH_DONE };

    Phase phase = PH_GREETING;

    // PING command
    const uint8_t PING[4] = {'P','I','N','G'};

    int ping_idx = 0;

    uint64_t total_ticks = 0;

    while (phase != PH_DONE) {

        drv.step();

        tick();

        total_ticks++;

        mon.step();

        if (total_ticks > SIM_TIMEOUT_CYC) {
            printf("\n[TB] ERROR: Simulation TIMEOUT\n");
            break;
        }

        // Test sequence state machine
        switch (phase) {

        case PH_GREETING:

            if (mon.hello_count >= 10) {
                printf("[TB] Greeting phase finished\n");
                phase = PH_PING_SEND;
            }
            break;

        case PH_PING_SEND:

            if (drv.is_idle() && ping_idx < 4)
                drv.enqueue(PING[ping_idx++]);

            if (drv.is_done() && ping_idx == 4) {
                printf("[TB] Waiting for echo response ...\n");
                phase = PH_ECHO_WAIT;
            }
            break;

        case PH_ECHO_WAIT:

            if (!rx_fifo.empty()) {

                uint8_t b = rx_fifo.front();
                rx_fifo.pop();

                printf("[TB] RX byte: %c\n", b);

                if (b == 'G') {
                    printf("\n============================================\n");
                    printf(" TEST PASSED\n");
                    printf(" Echo received : PING\n");
                    printf("============================================\n\n");

                    phase = PH_DONE;
                
            }
            break;

        default:
            break;
        }
    }

    tfp->close();

    delete tfp;
    delete top;

    return 0;
}
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                               

                                                                                                                                                                         


